### ISSUE TITLE
Width handle not working

### ISSUE THREAD

**Issue by CrisA-Works** [ivodolenc/aspekta#12]
### Steps to Reproduce

Open the variable font with FontBase or Illustrator
THe Width handle doesn't works

### Current Behavior

The variable version has a width handle but it doesn't work

### Expected Behavior

The handle should slide if the font has other widths

### Version

v2.000

**Comment by ivodolenc** [comment]
Hi, I'm not familiar with FontBase, but I just tested [`Aspekta Variable v2.000`](https://github.com/ivodolenc/aspekta/releases/tag/v2.000) in Illustrator and it works as expected.

https://github.com/ivodolenc/aspekta/assets/51852491/9a885d0b-23c0-40af-a768-ed64fac2edb0

**Comment by CrisA-Works** [comment]
That's the weight axis. I'm talking about the Width axis

**Comment by ivodolenc** [comment]
If you think of `width` as typeface width style, then this works as expected since Aspekta is primarily designed as a standard `sans-serif` font (only one `regular` width style).

This means that there are currently no predefined `condensed` or `wide` masters so that the `width` axes are always the same. You can only change the `weight` range.

**Comment by CrisA-Works** [comment]
Oh Ok. Are there plans for it to have more widths? In my opinion having a width slider in a typeface that doesn't has more widths it's kind of pointless.

**Comment by ivodolenc** [comment]
Just to clarify, as for the axis, this works as expected as I mentioned above in the comment.

When I started creating Aspekta, I had in mind to add `condensed` and `wide` masters, but since it takes a lot of time because you practically have to completely redesign the masters to match, I only did the `standard` version that is currently released.

If you want, you can safely remove the width axis from masters and export the font and everything will work the same as it does now.

I'm closing this because there are no errors.

**Comment by ivodolenc** [comment]
Just to note, axis `width` has been removed in the latest version `2.100` ( #26 ) to avoid possible confusion for now, since the `width` masters are not implemented yet.
