### ISSUE TITLE
Figma does not recognize it as a variable font

### ISSUE THREAD

**Issue by tjkohli** [ivodolenc/aspekta#15]
### Steps to Reproduce

Install font in Figma as an organization font

### Current Behavior

<img width="305" alt="Screenshot 2024-04-19 at 10 28 06 AM" src="https://github.com/ivodolenc/aspekta/assets/7361247/28962a38-b224-4c7b-b178-a9c4f2522a61">

### Expected Behavior

Show as a variable font (see Bacalar for example)

### Additional Details

This prevents us from being able to choose weights in Figma :(

### Version

2.0.0

**Comment by ivodolenc** [comment]
Hi, sorry for the late reply, I've been away for a while due to vacation. Thanks for you interest in `Aspekta Typeface`.

I just tested the font on the Figma Desktop platform and everything works fine. 

Also, on other Adobe desktop apps as well as on Sketch, the font works as expected (including variable and static fonts).

Can you share more details about the problem?

### Aspekta Variable

![Screenshot 2024-05-01 at 10 17 18](https://github.com/ivodolenc/aspekta/assets/51852491/1039aacb-02c9-4031-ad45-5cf161619544)

### Aspekta Stylistic Sets

![Screenshot 2024-05-01 at 10 18 57](https://github.com/ivodolenc/aspekta/assets/51852491/ed474286-5725-4f5f-b051-77e2a5fd66f9)

**Comment by ivodolenc** [comment]
Also, see this [comment](https://github.com/ivodolenc/aspekta/issues/12#issuecomment-1652536354), maybe clear up some possible confusion about font `weight` and `width (style)` axis as they are different terms.
