### ISSUE TITLE
Feat: Plans for extended latin glyphs? (Spanish)

### ISSUE THREAD

**Issue by alarcondgtuc** [ivodolenc/aspekta#2]
### Request Description

Hi! Amazing work! Looks super clean and Helvetica Neue like.

Question, are there plans on expanding to Spanish glyphs? Being a standard (in a way that could be used intensely for a lot of text) typeface I can't really use it on real projects as it is right now.

Congrats on the release!!!

### Alternative Solutions

Hm I haven't considered alternative solutions.

### Additional Details

 I found you trough fontesk.com

**Comment by ivodolenc** [comment]
Hi, thank you for your interest in this project and for the first star 😀

Yes, this is definitely on the [Roadmap](https://github.com/ivodolenc/aspekta/discussions/1). **Aspekta** is a new project, so I published it as a solid base for possible expansion in the future.

Since I'm from Croatia, I first added support for the Croatian and Slovenian languages, of course and the default English. Also, some special glyphs that I'm already working on are missing and I'll add them soon.

Unfortunately, I have no experience with Spanish language, so can you specify which glyphs are missing to fully support that language? That would be a huge help and save me time.

Let me give you an example of what I mean. The Croatian language has a couple of additional glyphs:

- `Č` - Ccaron
- `č` - ccaron
- `Ć` - Cacute
- `ć` - cacute
- `Ž` - Zcaron
- `ž` - zcaron
- `Š` - Scaron
- `š` - scaron
- `Đ` - Dcroat
- `đ` - dcroat

Following that example, all I need are the names of the missing Spanish glyphs.

Also, I didn't notice the post on the `Fontesk` page. They are fast! Awesome 😀

**Comment by alarcondgtuc** [comment]
Awesome! I'm glad I can help at something.

I'm not sure if these are all the Spanish special characters, but there are the most common:

**Accute accents:** [The most common]
-   `Á` - Accute accent capital A
-   `á` - Accute accent a
-   `É` - Accute accent capital E
-   `é` - Accute accent e
-   `Í` - Accute accent capital I
-   `í` - Accute accent i
-   `Ó` - Accute accent capital O
-   `ó` - Accute accent o
-   `Ú` - Accute accent capital U
-   `ú` - Accute accent u


**Tildes:** [Sometimes used]
-   `Ñ` - Tilded capital N
-   `ñ` - Tilded n

**Diaeresis:** [Very rarely used, I couldn't figure how to type it hah]
-   `Ü` - Diaeresis capital U
-   `ü` - Diaeresis u

**Comment by alarcondgtuc** [comment]
Closed it accidentally heh

**Comment by ivodolenc** [comment]
Ok thanks for your help 👍 

I don't think it will be a problem to add, more or less all the components are there except `Tilda`.

**Comment by ivodolenc** [comment]
I'm currently preparing shoots for the Showcase, but I think I might add it over the weekend.

**Comment by alarcondgtuc** [comment]
Awesome! I'll be here if you need anything else
